# Generated by Django 4.2.4 on 2023-12-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Галлерея", "verbose_name_plural": "Галлерея"},
        ),
    ]
