# Generated by Django 4.2.4 on 2024-09-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="blog_description",
            field=models.TextField(
                blank=True, max_length=250, verbose_name="Описание блога"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="users/%Y/%m/%d/", verbose_name="Фотография"
            ),
        ),
    ]
