# Generated by Django 4.2.4 on 2024-09-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                null=True, upload_to="users/%Y/%m/%d/", verbose_name="Фотография"
            ),
        ),
    ]
