# Generated by Django 4.2.4 on 2024-09-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/%Y/%m/%d/",
                verbose_name="Фотография",
            ),
        ),
    ]
