# Generated by Django 4.2.4 on 2024-10-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="Фотография"
            ),
        ),
    ]
