# Generated by Django 4.2.4 on 2023-12-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Название статьи"),
                ),
                ("summary", models.CharField(max_length=255, verbose_name="Анонс")),
                ("full_text", models.TextField(verbose_name="Полный текст")),
                (
                    "category",
                    models.CharField(max_length=255, verbose_name="Категория"),
                ),
                ("rubrica", models.CharField(blank=True, max_length=255, null=True)),
                ("pubdate", models.DateTimeField(verbose_name="Дата публикации")),
                ("slug", models.CharField(max_length=255, unique=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="images", verbose_name="Фотографии"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("d", "Draft"),
                            ("p", "Published"),
                            ("w", "Withdrawn"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "Статьи",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
