# Generated by Django 4.2.4 on 2024-09-21 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Название статьи"),
                ),
                ("summary", models.CharField(max_length=500, verbose_name="Анонс")),
                ("slug", models.CharField(max_length=255, unique=True)),
                ("full_text", models.TextField(verbose_name="Полный текст")),
                ("pubdate", models.DateTimeField(verbose_name="Дата публикации")),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="images", verbose_name="Фотографии"
                    ),
                ),
                ("publish", models.DateTimeField(default="UTC")),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="DF",
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-publish"],
                "indexes": [
                    models.Index(
                        fields=["-publish"], name="blog_articl_publish_2a54df_idx"
                    )
                ],
            },
        ),
    ]
