# Generated by Django 4.2.4 on 2023-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="status",
        ),
        migrations.AddField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Черновик"), (1, "Опубликовано")], default=0
            ),
        ),
    ]
