# Generated by Django 4.2.7 on 2023-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.CharField(max_length=255)),
                ("full_text", models.TextField()),
                ("category", models.TextField()),
                ("pubdate", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Articel",
        ),
    ]
