# Generated by Django 4.2.4 on 2024-09-21 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="pubdate",
        ),
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 21, 16, 53, 20, 375782, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последнее обнавление"
            ),
        ),
    ]
