# Generated by Django 4.2.4 on 2023-12-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="article",
            name="rubrica",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
