# Generated by Django 4.2.4 on 2023-12-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_image_alter_article_rubrica"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
