# Generated by Django 4.2.4 on 2024-09-22 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_image_alter_article_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 22, 11, 6, 50, 850779, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
    ]
