# Generated by Django 4.2.4 on 2024-09-28 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="course",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="image",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="module",
            name="course",
        ),
        migrations.RemoveField(
            model_name="text",
            name="owner",
        ),
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 28, 8, 40, 0, 460585, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Module",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Text",
        ),
    ]
