# Generated by Django 4.2.4 on 2024-09-28 08:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0019_remove_course_owner_remove_course_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 28, 8, 44, 49, 424748, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blogname", models.CharField(max_length=100)),
                ("blogauth", models.CharField(max_length=100)),
                ("blogdes", models.TextField(max_length=400)),
                ("img", models.ImageField(upload_to="pics")),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
