# Generated by Django 4.2.4 on 2024-09-28 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_alter_article_publish_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 28, 8, 47, 44, 852812, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="Фотографии"
            ),
        ),
    ]
