# Generated by Django 4.2.4 on 2024-09-28 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_alter_article_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 28, 9, 7, 28, 404237, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
        migrations.DeleteModel(
            name="Snippet",
        ),
    ]
