# Generated by Django 4.2.4 on 2024-09-28 14:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0024_alter_article_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/%Y/%m/%d/",
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 28, 14, 22, 44, 821235, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.CharField(max_length=255, unique=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Published")],
                default="DF",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.CharField(max_length=500, verbose_name="Превью"),
        ),
    ]
