# Generated by Django 4.2.4 on 2024-10-01 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0030_alter_article_image_alter_article_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images",
                verbose_name="Фотография превью",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 1, 14, 41, 37, 858016, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("DF", "Черновик"), ("PB", "Опубликовать")],
                default="DF",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
    ]
